version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8080:8080
  app:
    build: app
    links:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      LANG: C.UTF-8
      TZ: Europe/Moscow
    ports:
      - 5000:5000
    volumes:
      - ./logs:/logs